package calculator;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class CalculatorFrame extends javax.swing.JFrame {

    private History history;
    private AddController addController;
    private SubtractController subtractController;
    private MultiplyController multiplyController;
    private DivideController divideController;
    private PotencyController potencyController;
    private HistoryController historyController;

    public CalculatorFrame() {
        this.history = new History();
        Calculator model = new Calculator();
        addController = new AddController(model, this);
        subtractController = new SubtractController(model, this);
        multiplyController = new MultiplyController(model, this);
        divideController = new DivideController(model, this);
        potencyController = new PotencyController(model, this);
        historyController = new HistoryController(model, this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculator_title = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        subtract_button = new javax.swing.JButton();
        multiply_button = new javax.swing.JButton();
        divide_button = new javax.swing.JButton();
        potency_button = new javax.swing.JButton();
        clear_numbers_button = new javax.swing.JButton();
        update_history_button = new javax.swing.JButton();
        number1_textfield = new javax.swing.JTextField();
        number2_textfield = new javax.swing.JTextField();
        result_textfield = new javax.swing.JTextField();
        number1_label = new javax.swing.JLabel();
        number2_label = new javax.swing.JLabel();
        result_label = new javax.swing.JLabel();
        operation_history_jscroll = new javax.swing.JScrollPane();
        history_list_jlist = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calculator_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculator_title.setText("Calculator");

        add_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        subtract_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subtract_button.setText("Subtract");
        subtract_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtract_buttonActionPerformed(evt);
            }
        });

        multiply_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        multiply_button.setText("Multiply");
        multiply_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiply_buttonActionPerformed(evt);
            }
        });

        divide_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        divide_button.setText("Divide");
        divide_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_buttonActionPerformed(evt);
            }
        });

        potency_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        potency_button.setText("Potency");
        potency_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potency_buttonActionPerformed(evt);
            }
        });

        clear_numbers_button.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        clear_numbers_button.setText("Clear numbers");
        clear_numbers_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_numbers_buttonActionPerformed(evt);
            }
        });

        update_history_button.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        update_history_button.setText("Update history");
        update_history_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_history_buttonActionPerformed(evt);
            }
        });

        number1_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        number2_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        result_textfield.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        result_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        result_textfield.setEnabled(false);

        number1_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        number1_label.setText("Number 1");

        number2_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        number2_label.setText("Number 2");

        result_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        result_label.setText("Result");

        history_list_jlist.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        history_list_jlist.setEnabled(false);
        operation_history_jscroll.setViewportView(history_list_jlist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear_numbers_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(result_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(number1_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(number2_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(number1_textfield)
                            .addComponent(number2_textfield)
                            .addComponent(result_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(potency_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiply_button, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subtract_button, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(divide_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_history_button, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(operation_history_jscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(calculator_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculator_title)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1_label)
                    .addComponent(number1_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_history_button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(number2_label)
                            .addComponent(number2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(result_label)
                            .addComponent(result_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_button)
                            .addComponent(subtract_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divide_button)
                            .addComponent(multiply_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(potency_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear_numbers_button))
                    .addComponent(operation_history_jscroll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton de suma
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        addController.addOperation();
    }//GEN-LAST:event_add_buttonActionPerformed

    //Boton de resta
    private void subtract_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtract_buttonActionPerformed
        // TODO add your handling code here:
        subtractController.subtractOperation();
    }//GEN-LAST:event_subtract_buttonActionPerformed

    //Boton de multiplicar
    private void multiply_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiply_buttonActionPerformed
        // TODO add your handling code here:
        multiplyController.multiplyOperation();
    }//GEN-LAST:event_multiply_buttonActionPerformed

    //Boton de dividir
    private void divide_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide_buttonActionPerformed
        // TODO add your handling code here:
        divideController.divideOperation();
    }//GEN-LAST:event_divide_buttonActionPerformed

    //Boton de potencia
    private void potency_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potency_buttonActionPerformed
        // TODO add your handling code here:
        potencyController.potencyOperation();
    }//GEN-LAST:event_potency_buttonActionPerformed

    //Boton pa borrar los numeros
    private void clear_numbers_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_numbers_buttonActionPerformed
        // TODO add your handling code here:
        number1_textfield.setText("");
        number2_textfield.setText("");
        result_textfield.setText("");
    }//GEN-LAST:event_clear_numbers_buttonActionPerformed

    //Boton para actualizar el historial
    private void update_history_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_history_buttonActionPerformed
        // TODO add your handling code here:
        historyController.updateHistory();
    }//GEN-LAST:event_update_history_buttonActionPerformed

    //Obtener el numero del primer text field
    public String getNumber1() {
        return number1_textfield.getText();
    }

    //Obtener el numero del segundo text field
    public String getNumber2() {
        return number2_textfield.getText();
    }

    //Cambia el texto del label del resultado
    public void setResult(String result) {
        result_textfield.setText("" + result);
    }
    
    //Añade las operaciones al historial
    public void addHistory(Operation operation) {
        this.history.addOperation(operation);
    }
    
    //Retorna el historial
    public History getHistory() {
        return this.history;
    }
    
    //Establece el modelo de la lista del historial
    public void setHistoryModel(DefaultListModel model){
        this.history_list_jlist.setModel(model);
    }

    public void showErrorMessage(int error) {
        switch (error) {
            case 1: //Hay mas de 3 cifras decimales
                JOptionPane.showMessageDialog(null, "Los números digitados no deben contener mas de 3 dígitos decimales", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 2: //Numeros vacios
                JOptionPane.showMessageDialog(null, "Debe dígitar 2 números", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 3: //Hay algo que no sea numero
                JOptionPane.showMessageDialog(null, "Debe digitar solo números", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "Los números dígitados no deben superar los 3 dígitos", "Error", JOptionPane.ERROR_MESSAGE);

        }
        result_textfield.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel calculator_title;
    private javax.swing.JButton clear_numbers_button;
    private javax.swing.JButton divide_button;
    private javax.swing.JList<String> history_list_jlist;
    private javax.swing.JButton multiply_button;
    private javax.swing.JLabel number1_label;
    private javax.swing.JTextField number1_textfield;
    private javax.swing.JLabel number2_label;
    private javax.swing.JTextField number2_textfield;
    private javax.swing.JScrollPane operation_history_jscroll;
    private javax.swing.JButton potency_button;
    private javax.swing.JLabel result_label;
    private javax.swing.JTextField result_textfield;
    private javax.swing.JButton subtract_button;
    private javax.swing.JButton update_history_button;
    // End of variables declaration//GEN-END:variables
}
